server:
  port: 8080
spring:
  application:
    name: spring-ai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai-demo
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always